name: Update RSS Feed

on:
  schedule:
    - cron: '0 6 * * *'  # Dagelijks om 06:00 UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome 114
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_114.0.5735.90-1_amd64.deb

      - name: Install ChromeDriver 114
        run: |
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate RSS feed
        run: |
          python generate_rss.py

      - name: Commit and push RSS feed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add feed.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
