name: Update RSS Feed

on:
  schedule:
    - cron: '0 6 * * *'  # Dagelijks om 06:00 UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      # Stap 1: Checkout de repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Stap 2: Installeren van Google Chrome 100 (Verwijder eerst de bestaande versie)
      - name: Install Google Chrome 100
        run: |
          sudo apt-get update
          sudo apt-get remove -y google-chrome-stable
          sudo apt-get install -y wget
          wget https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_100.0.4896.127-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_100.0.4896.127-1_amd64.deb

      # Stap 3: Installeren van ChromeDriver 100
      - name: Install ChromeDriver 100
        run: |
          wget https://chromedriver.storage.googleapis.com/100.0.4896.60/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # Stap 4: Installeren van Python en dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Stap 5a: Genereer eerste RSS feed
      - name: Generate RSS feed (main)
        run: |
          python generate_rss.py

      # Stap 5b: Genereer tweede RSS feed
      - name: Generate RSS feed (extra)
        run: |
          python generate_rss2.py

      # Stap 6: Commit en push beide RSS feeds
      - name: Commit and push RSS feeds
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          [ -f feed_main.xml ] && git add feed_main.xml
          [ -f feed_extra.xml ] && git add feed_extra.xml
          git commit -m "Update both RSS feeds" || echo "No changes to commit"
          git push
